from django.urls import path
from .views import (
    api_admin_clients,
    api_admin_create_client,
    api_admin_update_client,
    api_admin_delete_client,
    api_admin_users,
    api_admin_create_user,
    api_admin_update_user,
    api_admin_delete_user,
    api_admin_access_info,
    api_admin_stats,
    api_admin_client_state,
    api_admin_step_upload,
    api_admin_step_file,
    api_admin_step_notes,
    api_admin_step_redo,
    api_admin_step_validate_835,
    api_admin_step_action,
    api_admin_client_documents,
    api_admin_client_documents_upload,
    api_admin_document_download,
    api_admin_document_delete,
    api_admin_client_edi_files,
    api_admin_client_test_environment,
    api_admin_golive_state,
    api_admin_golive_step_upload,
    api_admin_golive_step_download,
    api_admin_golive_step3_sftp,
    api_admin_golive_step4_schedule,
    api_admin_golive_step5_comment,
    api_admin_golive_step6_complete,
    api_admin_golive_step_redo,
    api_admin_test_environment_run,
    api_admin_employee_roles,
    api_mappings_view,
    api_mappings_check,
    api_mappings_reset,
    api_admin_client_smtp,
)

urlpatterns = [
    path("api/clients/", api_admin_clients, name="admin_api_clients"),
    path("api/clients", api_admin_clients),
    path("api/clients/create/", api_admin_create_client, name="admin_api_create_client"),
    path("api/clients/create", api_admin_create_client),
    path("api/clients/<uuid:client_id>/update/", api_admin_update_client, name="admin_api_update_client"),
    path("api/clients/<uuid:client_id>/delete/", api_admin_delete_client, name="admin_api_delete_client"),
    path("api/clients/<uuid:client_id>/state/", api_admin_client_state, name="admin_api_client_state"),
    path("api/clients/<uuid:client_id>/steps/<str:step_key>/upload/", api_admin_step_upload),
    path("api/clients/<uuid:client_id>/steps/<str:step_key>/file/", api_admin_step_file),
    path("api/clients/<uuid:client_id>/steps/<str:step_key>/notes/", api_admin_step_notes),
    path("api/clients/<uuid:client_id>/steps/<str:step_key>/redo/", api_admin_step_redo),
    path("api/clients/<uuid:client_id>/documents/", api_admin_client_documents),
    path("api/clients/<uuid:client_id>/documents/upload/", api_admin_client_documents_upload),
    path("api/documents/<uuid:doc_id>/download/", api_admin_document_download),
    path("api/documents/<uuid:doc_id>/", api_admin_document_delete),
    path("api/clients/<uuid:client_id>/edi-files/", api_admin_client_edi_files),
    path("api/clients/<uuid:client_id>/test-environment/", api_admin_client_test_environment),
    path("api/clients/<uuid:client_id>/test-environment/run-test/", api_admin_test_environment_run),
    path("api/clients/<uuid:client_id>/steps/step_7_835_val/validate-uploaded/", api_admin_step_validate_835),
    path("api/clients/<uuid:client_id>/steps/<str:step_key>/<str:action>/", api_admin_step_action),
    path("api/clients/<uuid:client_id>/golive/state/", api_admin_golive_state),
    path("api/clients/<uuid:client_id>/smtp/", api_admin_client_smtp, name="admin_api_client_smtp"),
    path("api/clients/<uuid:client_id>/golive/steps/<int:step_num>/upload/", api_admin_golive_step_upload),
    path("api/clients/<uuid:client_id>/golive/steps/<int:step_num>/download/", api_admin_golive_step_download),
    path("api/clients/<uuid:client_id>/golive/steps/3/sftp/", api_admin_golive_step3_sftp),
    path("api/clients/<uuid:client_id>/golive/steps/4/schedule/", api_admin_golive_step4_schedule),
    path("api/clients/<uuid:client_id>/golive/steps/5/comment/", api_admin_golive_step5_comment),
    path("api/clients/<uuid:client_id>/golive/steps/6/complete/", api_admin_golive_step6_complete),
    path("api/clients/<uuid:client_id>/golive/steps/<int:step_num>/redo/", api_admin_golive_step_redo),
    path("api/users/", api_admin_users, name="admin_api_users"),
    path("api/users", api_admin_users),
    path("api/users/create/", api_admin_create_user, name="admin_api_create_user"),
    path("api/users/create", api_admin_create_user),
    path("api/users/<int:user_id>/update/", api_admin_update_user, name="admin_api_update_user"),
    path("api/users/<int:user_id>/delete/", api_admin_delete_user, name="admin_api_delete_user"),
    path("api/access/info/", api_admin_access_info, name="admin_api_access_info"),
    path("api/access/info", api_admin_access_info),
    path("api/stats/", api_admin_stats, name="admin_api_stats"),
    path("api/stats", api_admin_stats),
    path("api/employee-roles/", api_admin_employee_roles, name="admin_api_employee_roles"),
    path("api/mappings/", api_mappings_view, name="admin_api_mappings"),
    path("api/mappings", api_mappings_view),
    path("api/mappings/check/", api_mappings_check, name="admin_api_mappings_check"),
    path("api/mappings/check", api_mappings_check),
    path("api/mappings/reset/", api_mappings_reset, name="admin_api_mappings_reset"),
    path("api/mappings/reset", api_mappings_reset),
]
