from django.urls import path
from .views import (
    api_admin_clients,
    api_admin_create_client,
    api_admin_update_client,
    api_admin_delete_client,
    api_admin_users,
    api_admin_create_user,
    api_admin_update_user,
    api_admin_delete_user,
    api_admin_access_info,
    api_admin_stats,
    api_admin_client_state,
    api_admin_step_upload,
    api_admin_step_file,
    api_admin_step_notes,
    api_admin_step_redo,
    api_admin_step_validate_835,
    api_admin_step_action,
    api_admin_client_documents,
    api_admin_client_documents_upload,
    api_admin_document_download,
    api_admin_document_delete,
    api_admin_client_edi_files,
)

urlpatterns = [
    path("api/clients/", api_admin_clients, name="admin_api_clients"),
    path("api/clients", api_admin_clients),
    path("api/clients/create/", api_admin_create_client, name="admin_api_create_client"),
    path("api/clients/create", api_admin_create_client),
    path("api/clients/<uuid:client_id>/update/", api_admin_update_client, name="admin_api_update_client"),
    path("api/clients/<uuid:client_id>/delete/", api_admin_delete_client, name="admin_api_delete_client"),
    path("api/clients/<uuid:client_id>/state/", api_admin_client_state, name="admin_api_client_state"),
    path("api/clients/<uuid:client_id>/steps/<str:step_key>/upload/", api_admin_step_upload),
    path("api/clients/<uuid:client_id>/steps/<str:step_key>/file/", api_admin_step_file),
    path("api/clients/<uuid:client_id>/steps/<str:step_key>/notes/", api_admin_step_notes),
    path("api/clients/<uuid:client_id>/steps/<str:step_key>/redo/", api_admin_step_redo),
    path("api/clients/<uuid:client_id>/documents/", api_admin_client_documents),
    path("api/clients/<uuid:client_id>/documents/upload/", api_admin_client_documents_upload),
    path("api/documents/<uuid:doc_id>/download/", api_admin_document_download),
    path("api/documents/<uuid:doc_id>/", api_admin_document_delete),
    path("api/clients/<uuid:client_id>/edi-files/", api_admin_client_edi_files),
    path("api/clients/<uuid:client_id>/steps/step_7_835_val/validate-uploaded/", api_admin_step_validate_835),
    path("api/clients/<uuid:client_id>/steps/<str:step_key>/<str:action>/", api_admin_step_action),
    path("api/users/", api_admin_users, name="admin_api_users"),
    path("api/users", api_admin_users),
    path("api/users/create/", api_admin_create_user, name="admin_api_create_user"),
    path("api/users/create", api_admin_create_user),
    path("api/users/<int:user_id>/update/", api_admin_update_user, name="admin_api_update_user"),
    path("api/users/<int:user_id>/delete/", api_admin_delete_user, name="admin_api_delete_user"),
    path("api/access/info/", api_admin_access_info, name="admin_api_access_info"),
    path("api/access/info", api_admin_access_info),
    path("api/stats/", api_admin_stats, name="admin_api_stats"),
    path("api/stats", api_admin_stats),
]
