# Generated by Django 6.1 on 2026-08-14 10:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EDI835File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for the file.', primary_key=True, serialize=False)),
                ('original_filename', models.CharField(help_text='Original uploaded filename.', max_length=255)),
                ('stored_filename', models.CharField(help_text='Unique physical filename.', max_length=255)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived'), ('ERROR', 'Error')], default='UPLOADED', help_text='Current processing state.', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Upload timestamp.')),
                ('processing_started_at', models.DateTimeField(blank=True, help_text='Processing start timestamp.', null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, help_text='Processing completion timestamp.', null=True)),
                ('input_path', models.CharField(blank=True, help_text='Input file location.', max_length=500, null=True)),
                ('output_path', models.CharField(blank=True, help_text='Generated MIR location.', max_length=500, null=True)),
                ('archive_path', models.CharField(blank=True, help_text='Archived file location.', max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error information if processing fails.', null=True)),
            ],
            options={
                'verbose_name': '835File',
                'verbose_name_plural': '835Files',
                'db_table': '835file',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
