# Generated by Django 6.1 on 2026-08-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edi835', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edi835file',
            name='claims_count',
            field=models.IntegerField(default=0, help_text='Number of claims in file.'),
        ),
        migrations.AddField(
            model_name='edi835file',
            name='records_count',
            field=models.IntegerField(default=0, help_text='Number of MIR records in file.'),
        ),
        migrations.AddField(
            model_name='edi835file',
            name='services_count',
            field=models.IntegerField(default=0, help_text='Number of service lines in file.'),
        ),
    ]
