# Generated by Django 6.1 on 2026-08-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edi835', '0002_edi835file_claims_count_edi835file_records_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edi835file',
            name='present_in_archive_folder',
            field=models.BooleanField(default=False, help_text='Boolean indicator if file is currently present in archive folder on disk.'),
        ),
        migrations.AddField(
            model_name='edi835file',
            name='present_in_sftp',
            field=models.BooleanField(default=False, help_text='Boolean indicator if file is currently present in SFTP/input folder.'),
        ),
    ]
