# Generated by Django 6.1 on 2026-08-14 15:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edi835', '0003_edi835file_present_in_archive_folder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SFTPConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='SFTP Connection', max_length=255)),
                ('connection_type', models.CharField(choices=[('UNIFIED', 'Unified SFTP'), ('INBOUND', 'Inbound SFTP'), ('OUTBOUND', 'Outbound SFTP')], default='UNIFIED', max_length=50)),
                ('use_same_server', models.BooleanField(default=True)),
                ('host', models.CharField(blank=True, default='sftp.example.com', max_length=255, null=True)),
                ('port', models.IntegerField(default=22)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_method', models.CharField(default='Password', max_length=50)),
                ('trust_unknown_key', models.BooleanField(default=True)),
                ('inbound_837_folder', models.CharField(blank=True, default='/relay/abc-health/in/837/', max_length=500, null=True)),
                ('inbound_835_folder', models.CharField(blank=True, default='/relay/abc-health/in/835/', max_length=500, null=True)),
                ('outbound_host', models.CharField(blank=True, max_length=255, null=True)),
                ('outbound_port', models.IntegerField(default=22)),
                ('outbound_username', models.CharField(blank=True, max_length=255, null=True)),
                ('outbound_password', models.CharField(blank=True, max_length=255, null=True)),
                ('outbound_auth_method', models.CharField(default='Password', max_length=50)),
                ('outbound_trust_unknown_key', models.BooleanField(default=True)),
                ('outbound_mir_folder', models.CharField(blank=True, default='/relay/abc-health/out/mir/', max_length=500, null=True)),
                ('status', models.CharField(default='NOT_CONFIGURED', max_length=50)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SFTP Configuration',
                'verbose_name_plural': 'SFTP Configurations',
                'db_table': 'sftp_config',
                'ordering': ['-updated_at'],
            },
        ),
    ]
