# Generated by Django 6.1 on 2026-08-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edi835', '0004_sftpconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='sftpconfig',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
