# Generated by Django 6.1 on 2026-08-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edi835', '0005_sftpconfig_last_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='sftpconfig',
            name='ssh_key',
            field=models.TextField(blank=True, help_text='SSH Private key string or path', null=True),
        ),
    ]
