# Generated by Django 6.1 on 2026-08-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edi835', '0006_sftpconfig_ssh_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='edi835file',
            name='ingestion_source',
            field=models.CharField(default='MANUAL', help_text='File ingestion origin: SFTP or MANUAL.', max_length=50),
        ),
    ]
