# Generated by Django 5.2.17 on 2026-08-21 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_client_claims_system_client_live_since_client_owner_and_more",
        ),
        ("edi835", "0007_edi835file_ingestion_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="edi835file",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Client associated with this file.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edi835_files",
                to="accounts.client",
            ),
        ),
    ]
