# Generated by Django 6.1 on 2026-08-21 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employeerole'),
        ('edi835', '0008_edi835file_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='sftpconfig',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client associated with this SFTP config.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sftp_configs', to='accounts.client'),
        ),
    ]
