# Generated by Django 6.1 on 2026-08-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_clientstepcomment_client_step_client__ab3a49_idx'),
        ('edi835', '0009_sftpconfig_client'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='edi835file',
            index=models.Index(fields=['client', '-uploaded_at'], name='D35file_client__bf8b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='edi835file',
            index=models.Index(fields=['status'], name='D35file_status_40f1b6_idx'),
        ),
    ]
