# Generated by Django 6.1 on 2026-08-20 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_client_claims_system_client_live_since_client_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoLiveStepDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingStepDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('performed_by', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.client')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClientTestEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sftp_host', models.CharField(default='sftp-test.internal', max_length=255)),
                ('sftp_username', models.CharField(max_length=255)),
                ('watched_folder', models.CharField(max_length=255)),
                ('test_status', models.CharField(default='In Progress', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_environment', to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientGoLiveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ERROR', 'Error')], default='PENDING', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golive_steps', to='accounts.client')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.golivestepdefinition')),
            ],
            options={
                'ordering': ['step__step_number'],
                'unique_together': {('client', 'step')},
            },
        ),
        migrations.CreateModel(
            name='ClientStepStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ERROR', 'Error')], default='PENDING', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_steps', to='accounts.client')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.onboardingstepdefinition')),
            ],
            options={
                'ordering': ['step__step_number'],
                'unique_together': {('client', 'step')},
            },
        ),
    ]
