# Generated by Django 5.2.17 on 2026-08-21 08:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_client_claims_system_client_live_since_client_owner_and_more",
        ),
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_name", models.CharField(max_length=255)),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "document_type",
                    models.CharField(default="General Document", max_length=100),
                ),
                ("file", models.FileField(upload_to="documents/")),
                ("file_size", models.IntegerField(default=0)),
                ("uploaded_by", models.CharField(default="Admin User", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="accounts.client",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
