# Generated by Django 6.1 on 2026-08-21 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_clientstepcomment"),
        ("admin_panel", "0002_clientdocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="MirMappingField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_id", models.CharField(max_length=50)),
                ("map_type", models.CharField(max_length=50)),
                ("map_value", models.TextField(blank=True, null=True)),
                ("length", models.IntegerField()),
                ("start", models.IntegerField()),
                ("upper", models.BooleanField(default=False)),
                ("trim", models.BooleanField(default=False)),
                ("truncate", models.BooleanField(default=False)),
                ("align", models.CharField(max_length=10)),
                ("pad", models.CharField(max_length=10)),
                (
                    "fallback_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("fallback_value", models.TextField(blank=True, null=True)),
                ("technical_rule", models.TextField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mir_mappings",
                        to="accounts.client",
                    ),
                ),
            ],
            options={
                "unique_together": {("client", "field_id")},
            },
        ),
    ]
