# Generated by Django 5.2.17 on 2026-08-21 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_user_assigned_clients_user_first_login"),
        ("admin_panel", "0003_mirmappingfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientSmtpConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(default="OneSmarter Support", max_length=255),
                ),
                (
                    "sender_email",
                    models.EmailField(default="support@onesmarter.com", max_length=254),
                ),
                (
                    "smtp_host",
                    models.CharField(default="smtp.gmail.com", max_length=255),
                ),
                ("smtp_port", models.IntegerField(default=587)),
                (
                    "smtp_username",
                    models.CharField(default="support@onesmarter.com", max_length=255),
                ),
                ("smtp_password", models.CharField(blank=True, max_length=255)),
                (
                    "security",
                    models.CharField(
                        choices=[
                            ("STARTTLS", "STARTTLS"),
                            ("SSL_TLS", "SSL / TLS"),
                            ("NONE", "None"),
                        ],
                        default="STARTTLS",
                        max_length=20,
                    ),
                ),
                ("reply_to", models.EmailField(blank=True, max_length=254, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smtp_config",
                        to="accounts.client",
                    ),
                ),
            ],
            options={
                "db_table": "client_smtp_config",
            },
        ),
    ]
