# Generated by Django 6.1 on 2026-08-22 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_client_stage"),
        ("admin_panel", "0004_clientsmtpconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="OffboardingStepDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["step_number"],
            },
        ),
        migrations.CreateModel(
            name="ClientOffboardingStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "document_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offboarding_steps",
                        to="accounts.client",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.offboardingstepdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["step__step_number"],
                "unique_together": {("client", "step")},
            },
        ),
    ]
