# Generated by Django 6.1 on 2026-08-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_clientstepcomment_client_step_client__ab3a49_idx'),
        ('admin_panel', '0005_offboardingstepdefinition_clientoffboardingstatus'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['client', '-timestamp'], name='admin_panel_client__809aad_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdocument',
            index=models.Index(fields=['client', 'document_type', '-created_at'], name='admin_panel_client__b66898_idx'),
        ),
    ]
