# Generated by Django 6.1 on 2026-08-20 17:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Client / Organization Name', max_length=255)),
                ('client_code', models.CharField(help_text='Unique Client Identifier', max_length=50, unique=True)),
                ('email', models.EmailField(help_text='Primary Contact Email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact Phone', max_length=50, null=True)),
                ('address', models.TextField(blank=True, help_text='Physical / Billing Address', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Administrative notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.client'),
        ),
    ]
