# Generated by Django 6.1 on 2026-08-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_user_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='claims_system',
            field=models.CharField(default='Vendor Hosted', help_text='Claims System (e.g., Epic, Facets)', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='live_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='owner',
            field=models.CharField(blank=True, help_text='Assigned admin user', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='progress_pct',
            field=models.IntegerField(default=0, help_text='Onboarding progress percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='client',
            name='stage',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('onboarding_completed', 'Onboarding Completed'), ('golive_pending', 'Go Live Pending'), ('production_pending', 'Production Pending'), ('production', 'Production')], default='onboarding', max_length=50),
        ),
    ]
