# Generated by Django 5.2.17 on 2026-08-21 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_employeerole"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientStepComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("step_number", models.IntegerField()),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("author", models.CharField(default="System", max_length=100)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_comments",
                        to="accounts.client",
                    ),
                ),
            ],
            options={
                "db_table": "client_step_comment",
                "ordering": ["-created_at"],
            },
        ),
    ]
