# Generated by Django 6.1 on 2026-08-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_clientstepcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="assigned_clients",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_admins", to="accounts.client"
            ),
        ),
    ]
