# Generated by Django 6.1 on 2026-08-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_assigned_clients"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="assigned_clients",
        ),
        migrations.AddField(
            model_name="user",
            name="first_login",
            field=models.BooleanField(default=True),
        ),
    ]
