# Generated by Django 6.1 on 2026-08-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_user_assigned_clients_user_first_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="stage",
            field=models.CharField(
                choices=[
                    ("onboarding", "Onboarding"),
                    ("onboarding_completed", "Onboarding Completed"),
                    ("golive_pending", "Go Live Pending"),
                    ("production_pending", "Production Pending"),
                    ("production", "Production"),
                    ("offboarded", "Offboarded"),
                ],
                default="onboarding",
                max_length=50,
            ),
        ),
    ]
