# Generated by Django 6.1 on 2026-08-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_client_stage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clientstepcomment',
            index=models.Index(fields=['client', 'step_number', '-created_at'], name='client_step_client__ab3a49_idx'),
        ),
    ]
