# Generated by Django 4.2.17 on 2026-08-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MirMappingField',
            fields=[
                ('field_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('map_type', models.CharField(max_length=50)),
                ('map_value', models.TextField(blank=True, null=True)),
                ('length', models.IntegerField()),
                ('start', models.IntegerField()),
                ('upper', models.BooleanField(default=False)),
                ('trim', models.BooleanField(default=False)),
                ('truncate', models.BooleanField(default=False)),
                ('align', models.CharField(max_length=10)),
                ('pad', models.CharField(max_length=10)),
                ('fallback_type', models.CharField(blank=True, max_length=50, null=True)),
                ('fallback_value', models.TextField(blank=True, null=True)),
                ('technical_rule', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
